name: Timesheets DB Build/Deploy staging
on:
  workflow_dispatch:

jobs:
  build-deploy-timesheets-DB-staging:
    name: Build/Deploy the timesheets database in staging account
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ssh 
        run: |
          mkdir -p ~/.ssh
          echo '${{secrets.TIMESHEETS_STAGING_SSH_PRIVATE_KEY}}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      
      - name: Setup ssh config 
        run: |
          private_ip=10.10.2.204
          echo $private_ip
          echo "Host timesheets_server_instance
          HostName timesheet.ts-stage.everest.engineering
          StrictHostKeyChecking no
          User ec2-user
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand none
          Host timesheets_database_instance
          HostName $private_ip
          StrictHostKeyChecking no
          User ec2-user
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand ssh timesheets_server_instance -W %h:%p" > ~/.ssh/config
          cat ~/.ssh/config

      - name: create inventory file
        run: |
          echo '[timesheets_database]
          timesheets_database_instance' > ~/inventory  